{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28d8fbc7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | default_exp _server"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7fcc07a5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "import asyncio\n",
    "import multiprocessing\n",
    "import signal\n",
    "import threading\n",
    "from contextlib import contextmanager\n",
    "from typing import *\n",
    "\n",
    "import asyncer\n",
    "import typer\n",
    "\n",
    "from fastkafka._components.helpers import _import_from_string\n",
    "from fastkafka._components.logger import get_logger"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "170ddd1c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from time import sleep\n",
    "\n",
    "from pydantic import BaseModel\n",
    "\n",
    "from fastkafka._components.logger import supress_timestamps\n",
    "from fastkafka._components.test_dependencies import generate_app_in_tmp\n",
    "from fastkafka.testing import LocalKafkaBroker"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62aaa890",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | notest\n",
    "\n",
    "# allows async calls in notebooks\n",
    "\n",
    "import nest_asyncio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55be7819",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | notest\n",
    "\n",
    "nest_asyncio.apply()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de03595b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "logger = get_logger(__name__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9ee8c91",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] __main__: ok\n"
     ]
    }
   ],
   "source": [
    "supress_timestamps()\n",
    "logger = get_logger(__name__, level=20)\n",
    "logger.info(\"ok\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a2d2a997",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "\n",
    "class ServerProcess:\n",
    "    def __init__(self, app: str):\n",
    "        self.app = app\n",
    "        self.should_exit = False\n",
    "\n",
    "    def run(self) -> None:\n",
    "        return asyncio.run(self._serve())\n",
    "\n",
    "    async def _serve(self) -> None:\n",
    "        self._install_signal_handlers()\n",
    "\n",
    "        self.application = _import_from_string(self.app)\n",
    "\n",
    "        async with self.application:\n",
    "            await self._main_loop()\n",
    "\n",
    "    def _install_signal_handlers(self) -> None:\n",
    "        if threading.current_thread() is not threading.main_thread():\n",
    "            raise RuntimeError()\n",
    "\n",
    "        loop = asyncio.get_event_loop()\n",
    "\n",
    "        HANDLED_SIGNALS = (\n",
    "            signal.SIGINT,  # Unix signal 2. Sent by Ctrl+C.\n",
    "            signal.SIGTERM,  # Unix signal 15. Sent by `kill <pid>`.\n",
    "        )\n",
    "\n",
    "        def handle_exit(sig: int) -> None:\n",
    "            self.should_exit = True\n",
    "\n",
    "        for sig in HANDLED_SIGNALS:\n",
    "            loop.add_signal_handler(sig, handle_exit, sig)\n",
    "\n",
    "    async def _main_loop(self) -> None:\n",
    "        while not self.should_exit:\n",
    "            await asyncio.sleep(0.1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ced70e01",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "_app = typer.Typer()\n",
    "\n",
    "\n",
    "@_app.command()\n",
    "def run_fastkafka_server_process(\n",
    "    app: str = typer.Argument(\n",
    "        ...,\n",
    "        help=\"input in the form of 'path:app', where **path** is the path to a python file and **app** is an object of type **FastKafka**.\",\n",
    "    )\n",
    ") -> None:\n",
    "    ServerProcess(app).run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e1de33fe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: make sure you save the notebook before running this cell\n",
      "\n",
      "Exporting and installing the new version of the CLI command...\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Obtaining file:///work/fastkafka\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: aiofiles>=22.1.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (23.1.0)\n",
      "Requirement already satisfied: aiokafka>=0.8.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (0.8.0)\n",
      "Requirement already satisfied: asyncer>=0.0.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (0.0.2)\n",
      "Requirement already satisfied: confluent-kafka>=1.9.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (2.0.2)\n",
      "Requirement already satisfied: docstring-parser>=0.15 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (0.15)\n",
      "Requirement already satisfied: fastcore>=1.5.27 in /usr/local/lib/python3.10/dist-packages (from fastkafka==0.1.1) (1.5.28)\n",
      "Requirement already satisfied: httpx>=0.23.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (0.23.3)\n",
      "Requirement already satisfied: install-jdk==0.3.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (0.3.0)\n",
      "Requirement already satisfied: ipywidgets>=8.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (8.0.4)\n",
      "Requirement already satisfied: nest-asyncio>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from fastkafka==0.1.1) (1.5.6)\n",
      "Requirement already satisfied: posix-ipc>=1.1.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.1.1)\n",
      "Requirement already satisfied: pydantic>=1.9 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.10.5)\n",
      "Requirement already satisfied: python-multipart>=0.0.5 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (0.0.6)\n",
      "Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.10/dist-packages (from fastkafka==0.1.1) (2.28.2)\n",
      "Requirement already satisfied: tqdm>=4.62 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (4.65.0)\n",
      "Requirement already satisfied: bandit==1.7.4 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.7.4)\n",
      "Requirement already satisfied: black==23.1.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (23.1.0)\n",
      "Requirement already satisfied: email-validator==1.3.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.3.1)\n",
      "Requirement already satisfied: isort==5.12.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (5.12.0)\n",
      "Requirement already satisfied: mypy==1.0.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.0.1)\n",
      "Requirement already satisfied: nbconvert==7.2.9 in /usr/local/lib/python3.10/dist-packages (from fastkafka==0.1.1) (7.2.9)\n",
      "Requirement already satisfied: nbdev-mkdocs==0.1.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (0.1.0)\n",
      "Requirement already satisfied: nbqa==1.6.3 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.6.3)\n",
      "Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from fastkafka==0.1.1) (1.24.2)\n",
      "Requirement already satisfied: pandas>=1.2.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.5.3)\n",
      "Requirement already satisfied: pre-commit==3.0.4 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (3.0.4)\n",
      "Requirement already satisfied: pytest==7.2.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (7.2.1)\n",
      "Requirement already satisfied: scikit-learn==1.2.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.2.1)\n",
      "Requirement already satisfied: semgrep==1.12.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from fastkafka==0.1.1) (1.12.1)\n",
      "Requirement already satisfied: GitPython>=1.0.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from bandit==1.7.4->fastkafka==0.1.1) (3.1.31)\n",
      "Requirement already satisfied: stevedore>=1.20.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from bandit==1.7.4->fastkafka==0.1.1) (5.0.0)\n",
      "Requirement already satisfied: PyYAML>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from bandit==1.7.4->fastkafka==0.1.1) (6.0)\n",
      "Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.10/dist-packages (from black==23.1.0->fastkafka==0.1.1) (3.0.0)\n",
      "Requirement already satisfied: pathspec>=0.9.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from black==23.1.0->fastkafka==0.1.1) (0.11.0)\n",
      "Requirement already satisfied: tomli>=1.1.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from black==23.1.0->fastkafka==0.1.1) (2.0.1)\n",
      "Requirement already satisfied: mypy-extensions>=0.4.3 in /home/tvrtko/.local/lib/python3.10/site-packages (from black==23.1.0->fastkafka==0.1.1) (1.0.0)\n",
      "Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.10/dist-packages (from black==23.1.0->fastkafka==0.1.1) (23.0)\n",
      "Requirement already satisfied: click>=8.0.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from black==23.1.0->fastkafka==0.1.1) (8.1.3)\n",
      "Requirement already satisfied: dnspython>=1.15.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from email-validator==1.3.1->fastkafka==0.1.1) (2.3.0)\n",
      "Requirement already satisfied: idna>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from email-validator==1.3.1->fastkafka==0.1.1) (3.4)\n",
      "Requirement already satisfied: typing-extensions>=3.10 in /home/tvrtko/.local/lib/python3.10/site-packages (from mypy==1.0.1->fastkafka==0.1.1) (4.5.0)\n",
      "Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (6.0.0)\n",
      "Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (0.2.2)\n",
      "Requirement already satisfied: traitlets>=5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (5.9.0)\n",
      "Requirement already satisfied: jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (3.1.2)\n",
      "Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (0.7.2)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (1.5.0)\n",
      "Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (2.14.0)\n",
      "Requirement already satisfied: mistune<3,>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (2.0.5)\n",
      "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (4.11.2)\n",
      "Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (1.2.1)\n",
      "Requirement already satisfied: jupyter-core>=4.7 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (5.2.0)\n",
      "Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (0.7.1)\n",
      "Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (2.1.2)\n",
      "Requirement already satisfied: nbformat>=5.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert==7.2.9->fastkafka==0.1.1) (5.7.3)\n",
      "Requirement already satisfied: docstring-gen>=0.2.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.2.2)\n",
      "Requirement already satisfied: mkdocstrings==0.18.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.18.1)\n",
      "Requirement already satisfied: mike>=1.1.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.1.2)\n",
      "Requirement already satisfied: mkdocs-literate-nav>=0.5.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.6.0)\n",
      "Requirement already satisfied: nbdev==2.3.12 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (2.3.12)\n",
      "Requirement already satisfied: mkdocs-section-index>=0.3.4 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.3.5)\n",
      "Requirement already satisfied: griffe>=0.24.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.25.5)\n",
      "Requirement already satisfied: mkdocs-material>=8.5.11 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (9.1.1)\n",
      "Requirement already satisfied: mkdocs>=1.4.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.4.2)\n",
      "Requirement already satisfied: typer[all]>=0.7.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.7.0)\n",
      "Requirement already satisfied: playwright>=1.28.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.31.1)\n",
      "Requirement already satisfied: configupdater>=3.1.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (3.1.1)\n",
      "Requirement already satisfied: ruamel.yaml>=0.17.21 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.17.21)\n",
      "Requirement already satisfied: openai>=0.25.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.27.0)\n",
      "Requirement already satisfied: tokenize-rt>=3.2.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from nbqa==1.6.3->fastkafka==0.1.1) (5.0.0)\n",
      "Requirement already satisfied: ipython>=7.8.0 in /usr/local/lib/python3.10/dist-packages (from nbqa==1.6.3->fastkafka==0.1.1) (8.10.0)\n",
      "Requirement already satisfied: cfgv>=2.0.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from pre-commit==3.0.4->fastkafka==0.1.1) (3.3.1)\n",
      "Requirement already satisfied: virtualenv>=20.10.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from pre-commit==3.0.4->fastkafka==0.1.1) (20.20.0)\n",
      "Requirement already satisfied: nodeenv>=0.11.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from pre-commit==3.0.4->fastkafka==0.1.1) (1.7.0)\n",
      "Requirement already satisfied: identify>=1.0.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from pre-commit==3.0.4->fastkafka==0.1.1) (2.5.18)\n",
      "Requirement already satisfied: iniconfig in /home/tvrtko/.local/lib/python3.10/site-packages (from pytest==7.2.1->fastkafka==0.1.1) (2.0.0)\n",
      "Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from pytest==7.2.1->fastkafka==0.1.1) (22.2.0)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /home/tvrtko/.local/lib/python3.10/site-packages (from pytest==7.2.1->fastkafka==0.1.1) (1.1.0)\n",
      "Requirement already satisfied: pluggy<2.0,>=0.12 in /home/tvrtko/.local/lib/python3.10/site-packages (from pytest==7.2.1->fastkafka==0.1.1) (1.0.0)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: joblib>=1.1.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from scikit-learn==1.2.1->fastkafka==0.1.1) (1.2.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from scikit-learn==1.2.1->fastkafka==0.1.1) (3.1.0)\n",
      "Requirement already satisfied: scipy>=1.3.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from scikit-learn==1.2.1->fastkafka==0.1.1) (1.10.1)\n",
      "Requirement already satisfied: wcmatch~=8.3 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (8.4.1)\n",
      "Requirement already satisfied: click-option-group~=0.5 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (0.5.5)\n",
      "Requirement already satisfied: glom~=22.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (22.1.0)\n",
      "Requirement already satisfied: python-lsp-jsonrpc~=1.0.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (1.0.0)\n",
      "Requirement already satisfied: jsonschema~=4.6 in /usr/local/lib/python3.10/dist-packages (from semgrep==1.12.1->fastkafka==0.1.1) (4.17.3)\n",
      "Requirement already satisfied: rich>=12.6.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (12.6.0)\n",
      "Requirement already satisfied: colorama~=0.4.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (0.4.6)\n",
      "Requirement already satisfied: boltons~=21.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (21.0.0)\n",
      "Requirement already satisfied: peewee~=3.14 in /home/tvrtko/.local/lib/python3.10/site-packages (from semgrep==1.12.1->fastkafka==0.1.1) (3.16.0)\n",
      "Requirement already satisfied: urllib3~=1.26 in /usr/local/lib/python3.10/dist-packages (from semgrep==1.12.1->fastkafka==0.1.1) (1.26.14)\n",
      "Requirement already satisfied: mkdocstrings-python-legacy>=0.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocstrings==0.18.1->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.2.2)\n",
      "Requirement already satisfied: Markdown>=3.3 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocstrings==0.18.1->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (3.3.7)\n",
      "Requirement already satisfied: mkdocs-autorefs>=0.3.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocstrings==0.18.1->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.4.1)\n",
      "Requirement already satisfied: pymdown-extensions>=6.3 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocstrings==0.18.1->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (9.10)\n",
      "Requirement already satisfied: asttokens in /usr/local/lib/python3.10/dist-packages (from nbdev==2.3.12->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (2.2.1)\n",
      "Requirement already satisfied: ghapi>=1.0.3 in /usr/local/lib/python3.10/dist-packages (from nbdev==2.3.12->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.0.3)\n",
      "Requirement already satisfied: execnb>=0.1.4 in /usr/local/lib/python3.10/dist-packages (from nbdev==2.3.12->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.1.5)\n",
      "Requirement already satisfied: watchdog in /usr/local/lib/python3.10/dist-packages (from nbdev==2.3.12->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (2.2.1)\n",
      "Requirement already satisfied: astunparse in /usr/local/lib/python3.10/dist-packages (from nbdev==2.3.12->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.6.3)\n",
      "Requirement already satisfied: kafka-python>=2.0.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from aiokafka>=0.8.0->fastkafka==0.1.1) (2.0.2)\n",
      "Requirement already satisfied: async-timeout in /home/tvrtko/.local/lib/python3.10/site-packages (from aiokafka>=0.8.0->fastkafka==0.1.1) (4.0.2)\n",
      "Requirement already satisfied: anyio<4.0.0,>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from asyncer>=0.0.2->fastkafka==0.1.1) (3.6.2)\n",
      "Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (from fastcore>=1.5.27->fastkafka==0.1.1) (23.0.1)\n",
      "Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.23.0->fastkafka==0.1.1) (1.3.0)\n",
      "Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from httpx>=0.23.0->fastkafka==0.1.1) (0.16.3)\n",
      "Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/tvrtko/.local/lib/python3.10/site-packages (from httpx>=0.23.0->fastkafka==0.1.1) (1.5.0)\n",
      "Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.23.0->fastkafka==0.1.1) (2022.12.7)\n",
      "Requirement already satisfied: jupyterlab-widgets~=3.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from ipywidgets>=8.0->fastkafka==0.1.1) (3.0.5)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets>=8.0->fastkafka==0.1.1) (6.21.2)\n",
      "Requirement already satisfied: widgetsnbextension~=4.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from ipywidgets>=8.0->fastkafka==0.1.1) (4.0.5)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from pandas>=1.2.0->fastkafka==0.1.1) (2022.7.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2.0->fastkafka==0.1.1) (2.8.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->fastkafka==0.1.1) (3.0.1)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from GitPython>=1.0.1->bandit==1.7.4->fastkafka==0.1.1) (4.0.10)\n",
      "Requirement already satisfied: face>=20.1.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from glom~=22.1->semgrep==1.12.1->fastkafka==0.1.1) (22.0.0)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /home/tvrtko/.local/lib/python3.10/site-packages (from httpcore<0.17.0,>=0.15.0->httpx>=0.23.0->fastkafka==0.1.1) (0.14.0)\n",
      "Requirement already satisfied: comm>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=8.0->fastkafka==0.1.1) (0.1.2)\n",
      "Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=8.0->fastkafka==0.1.1) (5.9.4)\n",
      "Requirement already satisfied: pyzmq>=20 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=8.0->fastkafka==0.1.1) (25.0.0)\n",
      "Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=8.0->fastkafka==0.1.1) (6.2)\n",
      "Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=8.0->fastkafka==0.1.1) (1.6.6)\n",
      "Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=8.0->fastkafka==0.1.1) (0.1.6)\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets>=8.0->fastkafka==0.1.1) (8.0.3)\n",
      "Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.18.2)\n",
      "Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.2.0)\n",
      "Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.7.5)\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (3.0.37)\n",
      "Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (4.8.0)\n",
      "Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (5.1.1)\n",
      "Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.6.2)\n",
      "Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema~=4.6->semgrep==1.12.1->fastkafka==0.1.1) (0.19.3)\n",
      "Requirement already satisfied: verspec in /home/tvrtko/.local/lib/python3.10/site-packages (from mike>=1.1.2->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.1.0)\n",
      "Requirement already satisfied: ghp-import>=1.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocs>=1.4.2->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (2.1.0)\n",
      "Requirement already satisfied: pyyaml-env-tag>=0.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocs>=1.4.2->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.1)\n",
      "Requirement already satisfied: mergedeep>=1.3.4 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocs>=1.4.2->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.3.4)\n",
      "Requirement already satisfied: regex>=2022.4.24 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocs-material>=8.5.11->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (2022.10.31)\n",
      "Requirement already satisfied: mkdocs-material-extensions>=1.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocs-material>=8.5.11->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.1.1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.1->nbconvert==7.2.9->fastkafka==0.1.1) (2.16.2)\n",
      "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from nodeenv>=0.11.1->pre-commit==3.0.4->fastkafka==0.1.1) (59.6.0)\n",
      "Requirement already satisfied: aiohttp in /home/tvrtko/.local/lib/python3.10/site-packages (from openai>=0.25.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (3.8.4)\n",
      "Requirement already satisfied: greenlet==2.0.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from playwright>=1.28.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (2.0.1)\n",
      "Requirement already satisfied: pyee==9.0.4 in /home/tvrtko/.local/lib/python3.10/site-packages (from playwright>=1.28.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (9.0.4)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->fastkafka==0.1.1) (1.16.0)\n",
      "Requirement already satisfied: ujson>=3.0.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from python-lsp-jsonrpc~=1.0.0->semgrep==1.12.1->fastkafka==0.1.1) (5.7.0)\n",
      "Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from rich>=12.6.0->semgrep==1.12.1->fastkafka==0.1.1) (0.9.1)\n",
      "Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in /home/tvrtko/.local/lib/python3.10/site-packages (from ruamel.yaml>=0.17.21->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.2.7)\n",
      "Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from stevedore>=1.20.0->bandit==1.7.4->fastkafka==0.1.1) (5.11.1)\n",
      "Requirement already satisfied: shellingham<2.0.0,>=1.3.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from typer[all]>=0.7.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.5.0.post1)\n",
      "Requirement already satisfied: filelock<4,>=3.4.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from virtualenv>=20.10.0->pre-commit==3.0.4->fastkafka==0.1.1) (3.9.0)\n",
      "Requirement already satisfied: distlib<1,>=0.3.6 in /home/tvrtko/.local/lib/python3.10/site-packages (from virtualenv>=20.10.0->pre-commit==3.0.4->fastkafka==0.1.1) (0.3.6)\n",
      "Requirement already satisfied: bracex>=2.1.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from wcmatch~=8.3->semgrep==1.12.1->fastkafka==0.1.1) (2.3.post1)\n",
      "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert==7.2.9->fastkafka==0.1.1) (2.4)\n",
      "Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->nbconvert==7.2.9->fastkafka==0.1.1) (0.5.1)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.1->bandit==1.7.4->fastkafka==0.1.1) (5.0.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.8.3)\n",
      "Requirement already satisfied: pytkdocs>=0.14 in /home/tvrtko/.local/lib/python3.10/site-packages (from mkdocstrings-python-legacy>=0.2->mkdocstrings==0.18.1->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.16.1)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.30->ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.2.6)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /home/tvrtko/.local/lib/python3.10/site-packages (from aiohttp->openai>=0.25.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.8.2)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/tvrtko/.local/lib/python3.10/site-packages (from aiohttp->openai>=0.25.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.3.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/tvrtko/.local/lib/python3.10/site-packages (from aiohttp->openai>=0.25.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (6.0.4)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/tvrtko/.local/lib/python3.10/site-packages (from aiohttp->openai>=0.25.0->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (1.3.3)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse->nbdev==2.3.12->nbdev-mkdocs==0.1.0->fastkafka==0.1.1) (0.37.1)\n",
      "Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (0.2.2)\n",
      "Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=7.8.0->nbqa==1.6.3->fastkafka==0.1.1) (1.2.0)\n",
      "Installing collected packages: fastkafka\n",
      "  Attempting uninstall: fastkafka\n",
      "    Found existing installation: fastkafka 0.1.1\n",
      "    Uninstalling fastkafka-0.1.1:\n",
      "      Successfully uninstalled fastkafka-0.1.1\n",
      "  Running setup.py develop for fastkafka\n",
      "Successfully installed fastkafka\n",
      "ok\n"
     ]
    }
   ],
   "source": [
    "# | notest\n",
    "\n",
    "print(\"WARNING: make sure you save the notebook before running this cell\\n\")\n",
    "\n",
    "print(\"Exporting and installing the new version of the CLI command...\")\n",
    "await asyncio.create_subprocess_exec(\"nbdev_export\")\n",
    "export_process = await asyncio.create_subprocess_exec(\"nbdev_export\")\n",
    "await export_process.wait()\n",
    "assert export_process.returncode == 0\n",
    "\n",
    "install_process = await asyncio.create_subprocess_exec(\n",
    "    \"pip\", \"install\", \"-e\", \"..[all]\"\n",
    ")\n",
    "await install_process.wait()\n",
    "assert install_process.returncode == 0\n",
    "\n",
    "print(\"ok\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e44f49ae",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "\n",
    "async def terminate_asyncio_process(p: asyncio.subprocess.Process) -> None:\n",
    "    logger.info(f\"terminate_asyncio_process(): Terminating the process {p.pid}...\")\n",
    "    # Check if SIGINT already propagated to process\n",
    "    try:\n",
    "        await asyncio.wait_for(p.wait(), 1)\n",
    "        logger.info(\n",
    "            f\"terminate_asyncio_process(): Process {p.pid} was already terminated.\"\n",
    "        )\n",
    "        return\n",
    "    except asyncio.TimeoutError:\n",
    "        pass\n",
    "\n",
    "    for i in range(3):\n",
    "        p.terminate()\n",
    "        try:\n",
    "            await asyncio.wait_for(p.wait(), 10)\n",
    "            logger.info(f\"terminate_asyncio_process(): Process {p.pid} terminated.\")\n",
    "            return\n",
    "        except asyncio.TimeoutError:\n",
    "            logger.warning(\n",
    "                f\"terminate_asyncio_process(): Process {p.pid} not terminated, retrying...\"\n",
    "            )\n",
    "\n",
    "    logger.warning(f\"Killing the process {p.pid}...\")\n",
    "    p.kill()\n",
    "    await p.wait()\n",
    "    logger.warning(f\"terminate_asyncio_process(): Process {p.pid} killed!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a5b0fe1a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] fastkafka._testing.local_broker: Java is already installed.\n",
      "[INFO] fastkafka._testing.local_broker: But not exported to PATH, exporting...\n",
      "[INFO] fastkafka._testing.local_broker: Kafka is already installed.\n",
      "[INFO] fastkafka._testing.local_broker: But not exported to PATH, exporting...\n",
      "[INFO] fastkafka._testing.local_broker: Starting zookeeper...\n",
      "[INFO] fastkafka._testing.local_broker: zookeeper started, sleeping for 5 seconds...\n",
      "[INFO] fastkafka._testing.local_broker: Starting kafka...\n",
      "[INFO] fastkafka._testing.local_broker: kafka started, sleeping for 5 seconds...\n",
      "[INFO] fastkafka._testing.local_broker: Local Kafka broker up and running on 127.0.0.1:9099\n",
      "[INFO] __main__: terminate_asyncio_process(): Terminating the process 279627...\n",
      "[INFO] __main__: terminate_asyncio_process(): Process 279627 terminated.\n",
      "[INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:9099'}'\n",
      "[INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:9099'}'\n",
      "[INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:9099'}'\n",
      "[INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:9099'}'\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:9099', 'group_id': '127.0.0.1:9099_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:9099', 'group_id': '127.0.0.1:9099_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'training_data'})\n",
      "[INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'training_data'}\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'realitime_data'})\n",
      "[INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'realitime_data'}\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:9099_group' (generation 1) with member_id aiokafka-0.8.0-fb8921b3-8e30-4c38-b227-059284e859ef\n",
      "[INFO] aiokafka.consumer.group_coordinator: Elected group leader -- performing partition assignments using roundrobin\n",
      "[WARNING] kafka.coordinator.assignors.roundrobin: No partition metadata for topic realitime_data\n",
      "[INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:9099_group with generation 1\n",
      "[INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:9099_group' (generation 2) with member_id aiokafka-0.8.0-e55f4208-d605-4a34-9504-65e28aaf944d\n",
      "[INFO] aiokafka.consumer.group_coordinator: Elected group leader -- performing partition assignments using roundrobin\n",
      "[INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:9099_group with generation 2\n",
      "[INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions {TopicPartition(topic='training_data', partition=0)} for group 127.0.0.1:9099_group\n",
      "[INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Terminating the process 279212...\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Process 279212 terminated.\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Terminating the process 278847...\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Process 278847 terminated.\n"
     ]
    }
   ],
   "source": [
    "with generate_app_in_tmp() as app:\n",
    "    async with LocalKafkaBroker(listener_port=9099) as bootstrap_server:\n",
    "        host_port = bootstrap_server.split(\":\")\n",
    "        os.environ[\"KAFKA_HOSTNAME\"] = host_port[0]\n",
    "        os.environ[\"KAFKA_PORT\"] = host_port[1]\n",
    "        proc = await asyncio.create_subprocess_exec(\n",
    "            \"run_fastkafka_server_process\", app, stdout=asyncio.subprocess.PIPE\n",
    "        )\n",
    "        sleep(5)\n",
    "        await terminate_asyncio_process(proc)\n",
    "        outputs, _ = await proc.communicate()\n",
    "\n",
    "        print(outputs.decode(\"utf-8\"))\n",
    "        assert proc.returncode == 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "52e1c583",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "\n",
    "async def run_fastkafka_server(num_workers: int, app: str) -> None:\n",
    "    loop = asyncio.get_event_loop()\n",
    "\n",
    "    HANDLED_SIGNALS = (\n",
    "        signal.SIGINT,  # Unix signal 2. Sent by Ctrl+C.\n",
    "        signal.SIGTERM,  # Unix signal 15. Sent by `kill <pid>`.\n",
    "    )\n",
    "\n",
    "    d = {\"should_exit\": False}\n",
    "\n",
    "    def handle_exit(sig: int, d: Dict[str, bool] = d) -> None:\n",
    "        d[\"should_exit\"] = True\n",
    "\n",
    "    for sig in HANDLED_SIGNALS:\n",
    "        loop.add_signal_handler(sig, handle_exit, sig)\n",
    "\n",
    "    async with asyncer.create_task_group() as tg:\n",
    "        tasks = [\n",
    "            tg.soonify(asyncio.create_subprocess_exec)(\n",
    "                \"run_fastkafka_server_process\",\n",
    "                app,\n",
    "                stdout=asyncio.subprocess.PIPE,\n",
    "                stdin=asyncio.subprocess.PIPE,\n",
    "            )\n",
    "            for i in range(num_workers)\n",
    "        ]\n",
    "\n",
    "    procs = [task.value for task in tasks]\n",
    "\n",
    "    async def log_output(\n",
    "        output: Optional[asyncio.StreamReader], pid: int, d: Dict[str, bool] = d\n",
    "    ) -> None:\n",
    "        if output is None:\n",
    "            raise RuntimeError(\"Expected StreamReader, got None. Is stdout piped?\")\n",
    "        while not output.at_eof():\n",
    "            outs = await output.readline()\n",
    "            if outs != b\"\":\n",
    "                typer.echo(f\"[{pid:03d}]: \" + outs.decode(\"utf-8\"), nl=False)\n",
    "\n",
    "    async with asyncer.create_task_group() as tg:\n",
    "        for proc in procs:\n",
    "            tg.soonify(log_output)(proc.stdout, proc.pid)\n",
    "\n",
    "        while not d[\"should_exit\"]:\n",
    "            await asyncio.sleep(0.2)\n",
    "\n",
    "        typer.echo(\"Starting process cleanup, this may take a few seconds...\")\n",
    "        for proc in procs:\n",
    "            tg.soonify(terminate_asyncio_process)(proc)\n",
    "\n",
    "    for proc in procs:\n",
    "        output, _ = await proc.communicate()\n",
    "        if output:\n",
    "            typer.echo(f\"[{proc.pid:03d}]: \" + output.decode(\"utf-8\"), nl=False)\n",
    "\n",
    "    returncodes = [proc.returncode for proc in procs]\n",
    "    if not returncodes == [0] * len(procs):\n",
    "        typer.secho(\n",
    "            f\"Return codes are not all zero: {returncodes}\",\n",
    "            err=True,\n",
    "            fg=typer.colors.RED,\n",
    "        )\n",
    "        raise typer.Exit(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "804d0df0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# | export\n",
    "\n",
    "\n",
    "@contextmanager\n",
    "def run_in_process(\n",
    "    target: Callable[..., Any]\n",
    ") -> Generator[multiprocessing.Process, None, None]:\n",
    "    p = multiprocessing.Process(target=target)\n",
    "    try:\n",
    "        p.start()\n",
    "        yield p\n",
    "    except Exception as e:\n",
    "        print(f\"Exception raised {e=}\")\n",
    "    finally:\n",
    "        p.terminate()\n",
    "        p.join()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f7c8cea8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] fastkafka._testing.local_broker: Java is already installed.\n",
      "[INFO] fastkafka._testing.local_broker: Kafka is already installed.\n",
      "[INFO] fastkafka._testing.local_broker: Starting zookeeper...\n",
      "[INFO] fastkafka._testing.local_broker: zookeeper started, sleeping for 5 seconds...\n",
      "[INFO] fastkafka._testing.local_broker: Starting kafka...\n",
      "[INFO] fastkafka._testing.local_broker: kafka started, sleeping for 5 seconds...\n",
      "[INFO] fastkafka._testing.local_broker: Local Kafka broker up and running on 127.0.0.1:10000\n",
      "[281803]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281805]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281807]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281803]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281805]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281803]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281807]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281803]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281805]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281805]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281807]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281809]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281803]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'realitime_data'})\n",
      "[281803]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'realitime_data'}\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281803]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'training_data'})\n",
      "[281803]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'training_data'}\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281807]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281807]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'realitime_data'})\n",
      "[281807]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'realitime_data'}\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281807]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'training_data'})\n",
      "[281807]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'training_data'}\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281805]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'training_data'})\n",
      "[281805]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'training_data'}\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281805]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'realitime_data'})\n",
      "[281805]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'realitime_data'}\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281809]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[281809]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281809]: [INFO] fastkafka._application.app: _create_producer() : created producer using the config: '{'bootstrap_servers': '127.0.0.1:10000'}'\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() starting...\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer created using the following parameters: {'bootstrap_servers': '127.0.0.1:10000', 'group_id': '127.0.0.1:10000_group', 'auto_offset_reset': 'earliest', 'max_poll_records': 100}\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281809]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'training_data'})\n",
      "[281809]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'training_data'}\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer started.\n",
      "[281809]: [INFO] aiokafka.consumer.subscription_state: Updating subscribed topics to: frozenset({'realitime_data'})\n",
      "[281809]: [INFO] aiokafka.consumer.consumer: Subscribed to topic(s): {'realitime_data'}\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer subscribed.\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[281803]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281803]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.cluster: Topic training_data not found in cluster metadata\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281805]: [WARNING] aiokafka.cluster: Topic training_data is not available during auto-create initialization\n",
      "[281807]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281807]: [WARNING] aiokafka.cluster: Topic realitime_data is not available during auto-create initialization\n",
      "[281809]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [ERROR] aiokafka.cluster: Topic realitime_data not found in cluster metadata\n",
      "[281803]: [ERROR] aiokafka.consumer.group_coordinator: Group Coordinator Request failed: [Error 15] CoordinatorNotAvailableError\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 1) with member_id aiokafka-0.8.0-1633a7bb-83e1-4090-a76a-4cab79db04ed\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Elected group leader -- performing partition assignments using roundrobin\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Metadata for topic has changed from {} to {'training_data': 1, 'realitime_data': 1}. \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 1) with member_id aiokafka-0.8.0-4a27292f-b3de-45bd-8304-33927ffa8b4e\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 1) with member_id aiokafka-0.8.0-0876af66-68f3-4f71-a7d0-550026bf69ad\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 1) with member_id aiokafka-0.8.0-cf7c9e2b-a4b3-4d20-9f22-46ec58a9c7dc\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 1) with member_id aiokafka-0.8.0-df0e12e0-c627-4860-bd18-501a0904dcc7\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Discovered coordinator 0 for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 1\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 1\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions {TopicPartition(topic='realitime_data', partition=0)} for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 1\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 1\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions {TopicPartition(topic='training_data', partition=0)} for group 127.0.0.1:10000_group\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 1\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281805]: [WARNING] aiokafka.consumer.group_coordinator: Heartbeat failed for group 127.0.0.1:10000_group because it is rebalancing\n",
      "[281807]: [WARNING] aiokafka.consumer.group_coordinator: Heartbeat failed for group 127.0.0.1:10000_group because it is rebalancing\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions frozenset() for group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281805]: [WARNING] aiokafka.consumer.group_coordinator: Heartbeat failed for group 127.0.0.1:10000_group because it is rebalancing\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions frozenset() for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281803]: [WARNING] aiokafka.consumer.group_coordinator: Heartbeat failed for group 127.0.0.1:10000_group because it is rebalancing\n",
      "[281809]: [WARNING] aiokafka.consumer.group_coordinator: Heartbeat failed for group 127.0.0.1:10000_group because it is rebalancing\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions frozenset() for group 127.0.0.1:10000_group\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions frozenset({TopicPartition(topic='realitime_data', partition=0)}) for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Revoking previously assigned partitions frozenset({TopicPartition(topic='training_data', partition=0)}) for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: (Re-)joining group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-1633a7bb-83e1-4090-a76a-4cab79db04ed\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Elected group leader -- performing partition assignments using roundrobin\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-0876af66-68f3-4f71-a7d0-550026bf69ad\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-4a27292f-b3de-45bd-8304-33927ffa8b4e\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-df0e12e0-c627-4860-bd18-501a0904dcc7\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-b63ee0d3-6149-4e84-9334-4b6e20837a79\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-3e827dd0-4393-42ba-b4d8-418f246ad2c1\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-cf7c9e2b-a4b3-4d20-9f22-46ec58a9c7dc\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Joined group '127.0.0.1:10000_group' (generation 2) with member_id aiokafka-0.8.0-7609bfe6-ee43-404d-ac08-585b5872c4da\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions {TopicPartition(topic='realitime_data', partition=0)} for group 127.0.0.1:10000_group\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions {TopicPartition(topic='training_data', partition=0)} for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Successfully synced group 127.0.0.1:10000_group with generation 2\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: Setting newly assigned partitions set() for group 127.0.0.1:10000_group\n",
      "Starting process cleanup, this may take a few seconds...\n",
      "[INFO] __main__: terminate_asyncio_process(): Terminating the process 281803...\n",
      "[INFO] __main__: terminate_asyncio_process(): Terminating the process 281805...\n",
      "[INFO] __main__: terminate_asyncio_process(): Terminating the process 281807...\n",
      "[INFO] __main__: terminate_asyncio_process(): Terminating the process 281809...\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281809]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281809]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[281807]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281807]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281803]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281803]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281805]: [INFO] aiokafka.consumer.group_coordinator: LeaveGroup request succeeded\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop(): Consumer stopped.\n",
      "[281805]: [INFO] fastkafka._components.aiokafka_consumer_loop: aiokafka_consumer_loop() finished.\n",
      "[INFO] __main__: terminate_asyncio_process(): Process 281809 terminated.\n",
      "[INFO] __main__: terminate_asyncio_process(): Process 281805 terminated.\n",
      "[INFO] __main__: terminate_asyncio_process(): Process 281803 terminated.\n",
      "[INFO] __main__: terminate_asyncio_process(): Process 281807 terminated.\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Terminating the process 281388...\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Process 281388 terminated.\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Terminating the process 281023...\n",
      "[INFO] fastkafka._components._subprocess: terminate_asyncio_process(): Process 281023 terminated.\n",
      "ok\n"
     ]
    }
   ],
   "source": [
    "# | notest\n",
    "\n",
    "async with LocalKafkaBroker(listener_port=10000) as bootstrap_server:\n",
    "    host_port = bootstrap_server.split(\":\")\n",
    "    os.environ[\"KAFKA_HOSTNAME\"] = host_port[0]\n",
    "    os.environ[\"KAFKA_PORT\"] = host_port[1]\n",
    "\n",
    "    with generate_app_in_tmp() as app:\n",
    "\n",
    "        def run_fastkafka_server_test():\n",
    "            asyncio.run(run_fastkafka_server(4, app))\n",
    "\n",
    "        with run_in_process(run_fastkafka_server_test) as p:\n",
    "            sleep(15)\n",
    "\n",
    "        assert p.exitcode == 0, p.exitcode\n",
    "        p.close()\n",
    "\n",
    "print(\"ok\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d11d7eb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "python3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
